name: Docker Hub Login

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Verify Docker login
        run: docker info
